### ISSUE TITLE
php.ini is missing

### ISSUE THREAD

**Issue by terdinatore** [Monogramm/docker-mautic#1]
**Describe the bug**
There is no `memory_limit` set in `php.ini`, so php defaults to 128M which ist not enough to run Mautic.  

**To Reproduce**
1. Pull monogramm/docker-mautic image
2. Run docker container with port attached
3. Open browser and navigate to port
4. See error: `Fatal error: Allowed memory size of 2097152 bytes exhausted (tried to allocate 36864 bytes) in /var/www/html/vendor/composer/autoload_static.php on line 4612`

My docker file is: 
```
version: '3'

services:
   mauticdb:
     container_name: ${CONTAINER_DB_NAME}
     image: mariadb:latest
     restart: unless-stopped
     volumes:
        - ${DB_PATH}:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}

   mautic:
     depends_on:
       - mauticdb
     container_name: ${CONTAINER_MT_NAME}
     image: monogramm/docker-mautic:apache
     restart: unless-stopped
     ports:
       - 80:80
     volumes:
       - ${MT_FILES}:/var/www/html
     environment:
       MAUTIC_DB_HOST: ${CONTAINER_DB_NAME}:3306
       MAUTIC_DB_NAME: ${MYSQL_DATABASE}
       MAUTIC_DB_USER: ${MYSQL_USER}
       MAUTIC_DB_PASSWORD: ${MYSQL_PASSWORD}
```

**Expected behavior**
Installer should start

**Docker (please complete the following information):**
 - Docker / Docker-compose Version: Docker version 18.09.5, build e8ff056dbc / docker-compose version 1.24.0, build 0aa59064
 - Image: monogramm/docker-mautic:apache

**Additional context**
You would be able to solve this by adding a php.ini file like this: 
```
always_populate_raw_post_data = -1
memory_limit = 2G
file_uploads = On
upload_max_filesize=128M
post_max_size=128M
date.timezone = ""
```
and copying it in the Dockerfile with `COPY php.ini /usr/local/etc/php/conf.d/php.ini`
